### ISSUE TITLE
Error if password contains /

### ISSUE THREAD

**Issue by uber1geek** [migonzalvar/dj-email-url#13]
If the password contains special characters such as ? or /, the following exception is raised (here I tried to use "foo/bar" as a password):

`ValueError: invalid literal for int() with base 10:`

**Comment by migonzalvar** [comment]
I'm afraid the `EMAIL_URL` wasn't a valid URL. If the password has special characters the solution is to replace those special characters in the password using the %xx escape. `dj-email-url` *unescapes* user and password as you can see in https://github.com/migonzalvar/dj-email-url/blob/master/dj_email_url.py#L75,L76
