### ISSUE TITLE
Mispelling of SMTPS in Warning

### ISSUE THREAD

**Issue by jeffmacdonald** [migonzalvar/dj-email-url#18]
https://github.com/migonzalvar/dj-email-url/blob/5727ca02f4f1ad8d3158ca702e084ba639c86fbe/dj_email_url.py#L96

Should smpts be smtps ?

Thanks!

**Comment by migonzalvar** [comment]
Fixed in f39527501f4afe528de40759f1c7f4217516a91c. Thank you
