### ISSUE TITLE
django-sendmail-backend

### ISSUE THREAD

**Issue by ad-m** [migonzalvar/dj-email-url#3]
I am want to start disqus about support django-sendmail-backend ( https://github.com/perenecabuto/django-sendmail-backend ) as new protocol. I am believe this is good idea due any strict connection. It will not add new requirements. 

I can implement and pull requests that.

**Comment by migonzalvar** [comment]
I'm not comfortable with the idea of adding email backends which are not in Django core or contrib.

I would be open to the idea of having an optional argument to `config()` and `parse()` with an extra dictionary mapping URL schemes with custom backends.

It would be something like this:

```python
def parse(url, extra_schemes=None):
    extra_schemes = extra_schemes or {}

    ...

    if url.scheme in SCHEMES:
        conf['EMAIL_BACKEND'] = SCHEMES[url.scheme]
    elif url.scheme in extra_schemes:
        conf['EMAIL_BACKEND'] = extra_schemes[url.scheme]

    ...
```

And the usage would be:

```python
parse('sendmail:', {'sendmail': 'django_sendmail_backend.backends.EmailBackend'})
```

What do you think? Would it solve your use case? Would you implement it?
